/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackLoginRouteImport } from './routes/callback/login'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ResponsePollIdIndexRouteImport } from './routes/response/$pollId/index'
import { Route as ProtectedPollIndexRouteImport } from './routes/_protected/poll/index'
import { Route as ProtectedPollPollIdIndexRouteImport } from './routes/_protected/poll/$pollId/index'
import { Route as ProtectedPollPollIdResultsRouteImport } from './routes/_protected/poll/$pollId/results'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackLoginRoute = CallbackLoginRouteImport.update({
  id: '/callback/login',
  path: '/callback/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ResponsePollIdIndexRoute = ResponsePollIdIndexRouteImport.update({
  id: '/response/$pollId/',
  path: '/response/$pollId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPollIndexRoute = ProtectedPollIndexRouteImport.update({
  id: '/poll/',
  path: '/poll/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPollPollIdIndexRoute =
  ProtectedPollPollIdIndexRouteImport.update({
    id: '/poll/$pollId/',
    path: '/poll/$pollId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPollPollIdResultsRoute =
  ProtectedPollPollIdResultsRouteImport.update({
    id: '/poll/$pollId/results',
    path: '/poll/$pollId/results',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/callback/login': typeof CallbackLoginRoute
  '/poll/': typeof ProtectedPollIndexRoute
  '/response/$pollId/': typeof ResponsePollIdIndexRoute
  '/poll/$pollId/results': typeof ProtectedPollPollIdResultsRoute
  '/poll/$pollId/': typeof ProtectedPollPollIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/callback/login': typeof CallbackLoginRoute
  '/poll': typeof ProtectedPollIndexRoute
  '/response/$pollId': typeof ResponsePollIdIndexRoute
  '/poll/$pollId/results': typeof ProtectedPollPollIdResultsRoute
  '/poll/$pollId': typeof ProtectedPollPollIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/callback/login': typeof CallbackLoginRoute
  '/_protected/poll/': typeof ProtectedPollIndexRoute
  '/response/$pollId/': typeof ResponsePollIdIndexRoute
  '/_protected/poll/$pollId/results': typeof ProtectedPollPollIdResultsRoute
  '/_protected/poll/$pollId/': typeof ProtectedPollPollIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/callback/login'
    | '/poll/'
    | '/response/$pollId/'
    | '/poll/$pollId/results'
    | '/poll/$pollId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/callback/login'
    | '/poll'
    | '/response/$pollId'
    | '/poll/$pollId/results'
    | '/poll/$pollId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/dashboard'
    | '/_protected/profile'
    | '/callback/login'
    | '/_protected/poll/'
    | '/response/$pollId/'
    | '/_protected/poll/$pollId/results'
    | '/_protected/poll/$pollId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  CallbackLoginRoute: typeof CallbackLoginRoute
  ResponsePollIdIndexRoute: typeof ResponsePollIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/login': {
      id: '/callback/login'
      path: '/callback/login'
      fullPath: '/callback/login'
      preLoaderRoute: typeof CallbackLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/response/$pollId/': {
      id: '/response/$pollId/'
      path: '/response/$pollId'
      fullPath: '/response/$pollId/'
      preLoaderRoute: typeof ResponsePollIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/poll/': {
      id: '/_protected/poll/'
      path: '/poll'
      fullPath: '/poll/'
      preLoaderRoute: typeof ProtectedPollIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/poll/$pollId/': {
      id: '/_protected/poll/$pollId/'
      path: '/poll/$pollId'
      fullPath: '/poll/$pollId/'
      preLoaderRoute: typeof ProtectedPollPollIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/poll/$pollId/results': {
      id: '/_protected/poll/$pollId/results'
      path: '/poll/$pollId/results'
      fullPath: '/poll/$pollId/results'
      preLoaderRoute: typeof ProtectedPollPollIdResultsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedPollIndexRoute: typeof ProtectedPollIndexRoute
  ProtectedPollPollIdResultsRoute: typeof ProtectedPollPollIdResultsRoute
  ProtectedPollPollIdIndexRoute: typeof ProtectedPollPollIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedPollIndexRoute: ProtectedPollIndexRoute,
  ProtectedPollPollIdResultsRoute: ProtectedPollPollIdResultsRoute,
  ProtectedPollPollIdIndexRoute: ProtectedPollPollIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  CallbackLoginRoute: CallbackLoginRoute,
  ResponsePollIdIndexRoute: ResponsePollIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
